### ISSUE TITLE
CS181 Fall 2022 HW 1 Q2

### ISSUE THREAD

**Issue by itsuitsuki** [i-TechX/iTechX#95]
![image](https://github.com/i-TechX/iTechX/assets/110326128/dd1eda05-8a53-4ea9-806f-d6430915b067)
I have some questions about the answer of this question. I think it may be UCS, because if this is BFS, logically, Q1 which has a different path will be a conflict. From the algorithm definitions we can also find that this may be UCS.

**Comment by why-in-Shanghaitech** [comment]
Hi, thank you for the question! According to the expansion rule, DFS is also possible. If the reference solution is not DFS + UCS, then it might be a bug. If so, could you please provide the link to this page? Thanks!

**Comment by itsuitsuki** [comment]
The link is https://i-techx.github.io/iTechX/reader?url=https://fastly.jsdelivr.net/gh/i-TechX/iTechX@file-base/courses/CS181/CS181.01_Fall_2022/Homework%20%E4%BD%9C%E4%B8%9A/Homework%201.mdx

Yes, it may be also DFS, in the case of alphabetical expansion for example. UCS & DFS is told "wrong" in the reference.

**Comment by why-in-Shanghaitech** [comment]
Thank you! This is absolutely a mistake. Thank you very much for pointing it out. It has been fixed in https://github.com/i-TechX/iTechX/commit/0ba2db2f40f28e8594bc716e3d680dca72b7699f

Due to the cache policy of jsdelivr, it could take up to 1 week to update the file. So recently the solution might still remain unchanged. This [link](https://i-techx.github.io/iTechX/reader?url=https://raw.githubusercontent.com/i-TechX/iTechX/file-base/courses/CS181/CS181.01_Fall_2022/Homework%20%E4%BD%9C%E4%B8%9A/Homework%201.mdx) does not use jsdelivr. You may check the updated solution (if you could open this page, it might be blocked).
